service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: customer-service-bq5o5jed
  name: customer-service-bq5o5jed
  selector: customer-service-bq5o5jed
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-customer-service-bq5o5jed
  storageClass: tlc-nfs-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: customer-service-bq5o5jed
    type: springboot
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: customer-service-bq5o5jed
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: customer-service-bq5o5jed
    port: 8080
  volume:
    name: pvc-customer-service-bq5o5jed
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
    mariadb:
      name: secret-mariadb-service-1-nraqqkxruc
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-customer-service-bq5o5jed
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
